.TH VPROC 1
.SH NAME
vproc \- graphical version of ps(1)
.SH SYNOPSIS
.B vproc
[
.I -a
]
[
.I -i
]
[
.I -h
]
[
.I -r
]
[
.I -d seconds
]
[
.I -s sortfmt
]
.SH DESCRIPTION
.I Vproc
displays information about processes.
.PP
The
.I \-a
flag causes vproc to also display the arguments passed to each process.
.PP
The
.I \-i
flag causes vproc to sort the list in a reverse order.
.PP
The
.I \-h
flag will print a usage messsage to standard output.
.PP
The
.I \-r
flag causes vproc to display the elapsed real time for each process.
.PP
The -s flag determines how the list should be sorted. If the flag is
not specified it will default to
.I
p
, which is the same behaviour as ps(1).
The
.I sortfmt
is expected to be one or more of the following:
.TF .
.TP
.B p
sort by the PID
.TP
.B U
sort by username
.TP
.B u
sort by user time
.TP
.B s
sort by system time
.TP
.B r
sort by real time
.TP
.B m
sort by memory usage
.TP
.B S
sort by the process state
.TP
.B c
sort by command name
.PD
.PP
Vproc will poll the
.I /proc
filesystem every 5 seconds,
this can be changed by setting the
.I \-d
flag. Note that the delay should be specified in seconds.
.SH EXAMPLES
.EX
vproc -i -d 1
.EE
.SH SEE ALSO
.EX
ps(1)
.EE
.SH BUGS
Yes.
