.TH VPROC 1
.SH NAME
vproc \- graphical version of ps(1)
.SH SYNOPSIS
.B vproc
[
.I -ahinr
]
[
.I -d seconds
]
[
.I -s sortfmt
]
.SH DESCRIPTION
.I Vproc
is a graphical tool that displays information about processes, it
scans the /proc file system every 5 seconds.
.PP
The
.I \-a
flag causes vproc to also display the arguments passed to each process.
.PP
The
.I \-d
flag specifies the sleep interval between each poll.
.PP
The
.I \-h
flag prints a usage messsage to standard output.
.PP
The
.I \-i
flag causes vproc to sort the list in a reversed order.
.PP
The
.I \-n
flag causes vproc to also display the note group of each process.
.PP
The
.I \-r
flag causes vproc to display the elapsed real time for each process.
.PP
The -s flag determines how the list should be sorted.  If the flag is
not specified it will default to
.I
p
, which is the same behaviour as ps(1).
The
.I sortfmt
is expected to be one or more of the following:
.TF .
.TP
.B p
sort by the PID
.TP
.B U
sort by username
.TP
.B u
sort by user time
.TP
.B s
sort by system time
.TP
.B r
sort by real time
.TP
.B m
sort by memory usage
.TP
.B S
sort by the process state
.TP
.B c
sort by command name
.PD
.SH EXAMPLES
.PP
Reverse sort the list (so that the highest PID is at the top) and
sleep only one second between each poll.
.EX
vproc -i -d 1
.EE
.SH SEE ALSO
.EX
ps(1)
.EE
.SH BUGS
Yes.
